### ISSUE TITLE
New route syntax

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#1]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/routes/web.php#L20

Būtų gerai priprasti rašyti route su nauja sintakse, 

```
Route::get('/home', ['HomeController', 'index'])->name('home');
```

Nes ateityje, su naujesnėm Laravel versijom, tai bus vienintelis žinomas standartas, ir bus lengviau komandoje skaityti kodą.

**Comment by viktorasbuivydas** [comment]
fixed
