### ISSUE TITLE
Unique validation

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#10]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/app/Http/Controllers/User/BookController.php#L46

Šitas dalykas turėtų būti validacijos klasėje Form Request, panaudotas `unique` rule turėtų būti

**Comment by viktorasbuivydas** [comment]
fixed
