### ISSUE TITLE
auth id

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#13]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/app/Http/Controllers/User/ReportController.php#L18

Galima trumpiau iš bet kokio failo tą pasiekti: `auth()->id()`

Tada nereikės viršuje
`use Illuminate\Support\Facades\Auth;`

**Comment by viktorasbuivydas** [comment]
fixed
