### ISSUE TITLE
auth user

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#14]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/app/Http/Controllers/User/SettingController.php#L28

Nereikia traukti iš duombazės.
Bet kur kur tau reikia prisijungusio userio, yra `auth()->user()`

Pvz jei reikia emailo, tai `auth()->user()->email`

Jei reikia updatinti duomenis `auth()->user()->update($array)`

**Comment by viktorasbuivydas** [comment]
fixed
