### ISSUE TITLE
author_book

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#15]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/app/Book.php#L19

Geriau DB lentelę vadinti pagal Laravel pivot standartus, ir nereikės tada kaip parametro čionai nurodyti.
Gali pažiūrėti: https://www.youtube.com/watch?v=V5xINbA-z9o

**Comment by viktorasbuivydas** [comment]
fixed
