### ISSUE TITLE
use Middleware

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#2]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/routes/web.php#L4

Man atrodo nereikia čia šito use, nes checkRole pagal vardą po to eina kreipinys, kuris Kernel užregistruojamas.

**Comment by viktorasbuivydas** [comment]
fixed
