### ISSUE TITLE
Three queries

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#3]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/app/Http/Controllers/HomeController.php#L29

Čia aišku mažas pavyzdys ir labai neapkrauna duomenų bazės, bet manau efektyviau, dirbant ateityje, būtų padaryti vieną query į DB, pvz `Book::select('approved')->get();` ir tada tuos tris išgauti jau iš kolekcijos, pvz `$approved_book_count = $books->where('approved', 1)->count();`

**Comment by viktorasbuivydas** [comment]
fixed
