### ISSUE TITLE
Empty lines between methods

### ISSUE THREAD

**Issue by PovilasKorop** [viktorasbuivydas/Bookshop#9]
https://github.com/viktorasbuivydas/Bookshop/blob/9cc1fe6149affb29dbd5356c7130fefec6819517/app/Http/Controllers/User/BookController.php#L36

Kodo stilius/formatavimas
Pala, tai kiek tuščių eilučių reikia tarp metodų? Pas tave yra ir 0, ir 1, ir 2 :)

Turėtų būti viena eilutė visur.

**Comment by viktorasbuivydas** [comment]
fixed
